# Dependencies
markdown: kramdown

# Setup
title: sarah c y
subtitle: sarahseewhy
description: >-
 developer | historian
baseurl: ""
url: http:sarahseewhy.github.io
username: sarahseewhy
email: sarahseewhy@gmail.com
# Links
links:
 - url: https://github.com/
   logo: github
 - url: https://twitter.com/
   logo: twitter
 - url: https://linkedin.com/in/
   logo: linkedin

# Plugins
plugins:
  - jekyll-feed