# Dependencies
markdown: kramdown

# Setup
title: sarah c y
email: sarahseewhy@gmail.com
description: >-
  Historian by training, developer by choice, curious by nature.
baseurl: /some_url
url: ""
twitter_username: sarahseewhy
github_username:  sarahseewhy
paginate: 5

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
