# Dependencies
markdown: kramdown

# Setup
title: sarah c y
subtitle: sarahseewhy
email: sarahseewhy@gmail.com
description: >-
 developer | historian
baseurl: ""
url: http:sarahseewhy.github.io

twitter_username: sarahseewhy
github_username:  sarahseewhy

# Plugins
plugins:
  - jekyll-feed