# Dependencies
markdown: kramdown

# Setup
title: sarah c y
email: sarahseewhy@gmail.com
description: >-
 developer

baseurl: ""
url: http:sarahseewhy.github.io

twitter_username: sarahseewhy
github_username:  sarahseewhy
paginate: 10
paginate_path: "/page/:num/"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
