# Dependencies
markdown: kramdown
# Setup
title: tech etc...
subtitle: sarah young
description: >-
 sre | dev | historian
baseurl: ""
url: http:sarahseewhy.github.io
username: sarahseewhy
email: sarahseewhy@gmail.com
# Links
links:
 - url: https://github.com/
   logo: github
 - url: https://linkedin.com/in/
   logo: linkedin
# Plugins
plugins:
  - jekyll-feed

# default excludes
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - gems/ruby